### ISSUE TITLE
[Bug] No Syphon video output

### ISSUE THREAD

**Issue by LucieMrc** [Augmenta-tech/AugmentaFusion-issueTracker#11]
**Describe the bug** : 
No Syphon video output is created when I enable the Video Output of my scene.

**To Reproduce Steps to reproduce the behavior:**
Go to Scene, open the Video Output.
Open Syphon.

**Expected behavior :** 
Finding a video on Syphon after enabling the Video Output.

**Desktop (please complete the following information):**

OS: Mac OS 11.4
Software version: 2.2.1

**Comment by Lyptik** [comment]
Hello Lucie,

Did you try with the latest beta of Fusion ? (you can opt-in beat in the preferences)

Also can you try with NDI ? If we needed you can use a free tool like Syphon 2 NDI

Hope it can be a quick fix for your problem.

Best

**Comment by LucieMrc** [comment]
It worked with the latest beta with NDI ! Thanks !
