### ISSUE TITLE
[Bug] spell check bug

### ISSUE THREAD

**Issue by Lyptik** [Augmenta-tech/AugmentaFusion-issueTracker#3]
**Describe the bug**
It would be more correct to replace "Add all 1 sources" by "Add 1 source"

**Screenshots**
![image](https://user-images.githubusercontent.com/5172593/153911001-e6468948-fedc-41ae-9d7d-31d9f5550813.png)

**Comment by benkuper** [comment]
Or Add all (1 source) ?

**Comment by Lyptik** [comment]
Sounds even better imo
